#!/usr/bin/env zsh

pandoc-tangle --from markdown --to code-maude --code meta-strategy            meta-strategy.md > meta-strategy.maude
pandoc-tangle --from markdown --to code-maude --code example-cycle            meta-strategy.md > cycle.maude
pandoc-tangle --from markdown --to code-maude --code example-nondet-scheduler meta-strategy.md > nondet-scheduler.maude
